version: '3'

services:
  docusaurus:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - './docs:/app/docs'
      - './src:/app/src'
      - './static:/app/static'
      - './docusaurus.config.js:/app/docusaurus.config.js'
      - './sidebars.js:/app/sidebars.js'
      - '.:/app/'
    command:
        - /bin/sh
        - -c
        - |
          npm cache clean --force
          npm install --verbose
          npm run build
          npm run serve -- --port 8000